### ISSUE TITLE
upgrades kernel without upgrading vbox guest additions

### ISSUE THREAD

**Issue by lo5an** [OULibraries/ansible-role-centos7#15]
It works great when you first boot the machine, but then our provisioners update the kernel on the machine and we don't do anything to update the virtualbox guest additions.
I remembered tracking it down to an unloaded kernel module last time, and this time I noticed that the only vboxsf module was for an older kernel than the one currently running. make install in the guest additions source folder fixed it and it seems to be happy now.

**Comment by jsnshrmn** [comment]
Closed by 1d3d252
