### ISSUE TITLE
sometimes tries to install nonexistant kernel-headers and kernel-devel packages

### ISSUE THREAD

**Issue by lo5an** [OULibraries/ansible-role-centos7#23]
Sometimes, we get a new CentOS kernel release with no update to `kernel-devel` or `kernel-headers`.  Right now, for example:

```
$ rpm -qa | grep kernel
kernel-devel-3.10.0-514.2.2.el7.x86_64
kernel-tools-libs-3.10.0-514.2.2.el7.x86_64
kernel-tools-3.10.0-514.2.2.el7.x86_64
kernel-headers-3.10.0-514.2.2.el7.x86_64
kernel-3.10.0-327.el7.x86_64
kernel-3.10.0-327.22.2.el7.x86_64
```

This results in the role failing out on virtualbox while trying to install non-existent `kernel-devel` or `kernel-headers` packages.

**Comment by lo5an** [comment]
Temp duct tape is to add `ignore_errors: yes` to the relevant tasks.

**Comment by jsnshrmn** [comment]
duct-taped by  commit dda9527
